apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scala-steward.fullname" . }}-configmap
data:
  repos.md: |
    {{- range .Values.repos }}
    - {{ . }}
    {{- end }}
  password.sh: |
    {{- tpl (.Files.Get "files/password.sh") . | nindent 4 }}
  scalafix.conf: |
    {{- .Values.scalafixConfig | nindent 4 }}
