{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scala-steward.pvcName" . }}
  annotations:
    {{- include "scala-steward.labels" . | nindent 4 }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ with .Values.persistence.className }}
  storageClassName: {{ quote . }}
  {{- end }}
{{- end }}
