{{ if not .Values.existingGitSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scala-steward.fullname" . }}-secret
type: Generic
stringData:
  gitSecret: {{ .Values.gitSecret | quote }}
{{ end }}
